version: '3.8'

services:
  housecrush:
    build: .
    ports:
      - "7860:7860"
    environment:
      - FLASK_ENV=development
      - PORT=7860
      # Debug settings (enabled in development)
      - ENABLE_DEBUG_LOGGING=true
      - ENABLE_FILE_LOGGING=true
      - ENABLE_DEBUG_FILES=true
      - ENABLE_FEEDBACK_LOGGING=true
      # Add your API keys here or use a .env file
      # - TOGETHER_API_KEY=your_key_here
      # - GOOGLE_API_KEY=your_key_here
      # - GOOGLE_SEARCH_ENGINE_ID=your_search_engine_id_here
    env_file:
      - .env
    volumes:
      - ./results:/app/results
      - ./logs:/app/logs
      - ./debug:/app/debug
      - ./tmp:/app/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 